codecov:
  require_ci_to_pass: yes
  token: 374fa3cd-d594-4f71-87ba-015cd014a0bd

coverage:
  precision: 2
  round: down
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

ignore:
  - "src/main/kotlin/br/com/devlhse/kotlinauthservice/application/**/*"
  - "src/main/kotlin/br/com/devlhse/kotlinauthservice/application/Main.kt"
  - "src/main/kotlin/br/com/devlhse/kotlinauthservice/config"
  - "src/main/kotlin/br/com/devlhse/kotlinauthservice/domain/model/**/*"
  - "src/main/kotlin/br/com/devlhse/kotlinauthservice/domain/repositories/**/*"
  - "src/main/kotlin/br/com/devlhse/kotlinauthservice/domain/services/UserService.kt"
  - "src/main/kotlin/br/com/devlhse/kotlinauthservice/exception"
  - "src/main/kotlin/br/com/devlhse/kotlinauthservice/resources/tables/**/*"
  - "src/main/kotlin/br/com/devlhse/kotlinauthservice/resources/clients/**/*"