###

GET http://localhost:7000/health-check HTTP/1.1
Content-Type: application/json

###

GET http://localhost:7000/health-check/complete HTTP/1.1
Content-Type: application/json

###

GET http://localhost:7000/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZUB0ZXN0ZS5jb20uYnIiLCJyb2xlIjoiQVVUSEVOVElDQVRFRCIsImV4cCI6MTU5NzUyMTYwMywiaWF0IjoxNTk3NTE4MDAzfQ.i8Yzp5LI4UDg6nOF1EbY-iji8IuzbIN8K7PPi47Brvw
###

POST http://localhost:7000/users HTTP/1.1
content-type: application/json

{
   "user":{
      "name":"testelh",
      "email":"teste@teste.com.br",
      "password":"testando"
   }
}

###

POST http://localhost:7000/users/login HTTP/1.1
content-type: application/json

{
   "user":{
      "name":"testelh",
      "email":"teste@teste.com.br",
      "password":"testando"
   }
}